// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/RadarFc2_AckMsg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @brief  List of acknowledgement codes
type RadarAckMsg_CodeType int32

const (
	RadarAckMsg_CodeType_ACK_RESERVED   RadarAckMsg_CodeType = 0
	RadarAckMsg_CodeType_ACK_UNDEFINED  RadarAckMsg_CodeType = 1
	RadarAckMsg_CodeType_ACK_DECODE     RadarAckMsg_CodeType = 2
	RadarAckMsg_CodeType_ACK_GENERAL    RadarAckMsg_CodeType = 3
	RadarAckMsg_CodeType_ACK_WORK_STATE RadarAckMsg_CodeType = 4
)

// Enum value maps for RadarAckMsg_CodeType.
var (
	RadarAckMsg_CodeType_name = map[int32]string{
		0: "ACK_RESERVED",
		1: "ACK_UNDEFINED",
		2: "ACK_DECODE",
		3: "ACK_GENERAL",
		4: "ACK_WORK_STATE",
	}
	RadarAckMsg_CodeType_value = map[string]int32{
		"ACK_RESERVED":   0,
		"ACK_UNDEFINED":  1,
		"ACK_DECODE":     2,
		"ACK_GENERAL":    3,
		"ACK_WORK_STATE": 4,
	}
)

func (x RadarAckMsg_CodeType) Enum() *RadarAckMsg_CodeType {
	p := new(RadarAckMsg_CodeType)
	*p = x
	return p
}

func (x RadarAckMsg_CodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RadarAckMsg_CodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_RadarFc2_AckMsg_proto_enumTypes[0].Descriptor()
}

func (RadarAckMsg_CodeType) Type() protoreflect.EnumType {
	return &file_proto_RadarFc2_AckMsg_proto_enumTypes[0]
}

func (x RadarAckMsg_CodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RadarAckMsg_CodeType.Descriptor instead.
func (RadarAckMsg_CodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_RadarFc2_AckMsg_proto_rawDescGZIP(), []int{0}
}

// @brief  Radar acknowledge message type
type RadarAckMsgType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnuAckCode  RadarAckMsg_CodeType `protobuf:"varint,1,opt,name=enuAckCode,proto3,enum=RadarFc2_AckMsg.RadarAckMsg_CodeType" json:"enuAckCode,omitempty"`
	U32AAckData []uint32             `protobuf:"varint,2,rep,packed,name=u32aAckData,proto3" json:"u32aAckData,omitempty"`
}

func (x *RadarAckMsgType) Reset() {
	*x = RadarAckMsgType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RadarFc2_AckMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RadarAckMsgType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarAckMsgType) ProtoMessage() {}

func (x *RadarAckMsgType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RadarFc2_AckMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarAckMsgType.ProtoReflect.Descriptor instead.
func (*RadarAckMsgType) Descriptor() ([]byte, []int) {
	return file_proto_RadarFc2_AckMsg_proto_rawDescGZIP(), []int{0}
}

func (x *RadarAckMsgType) GetEnuAckCode() RadarAckMsg_CodeType {
	if x != nil {
		return x.EnuAckCode
	}
	return RadarAckMsg_CodeType_ACK_RESERVED
}

func (x *RadarAckMsgType) GetU32AAckData() []uint32 {
	if x != nil {
		return x.U32AAckData
	}
	return nil
}

var File_proto_RadarFc2_AckMsg_proto protoreflect.FileDescriptor

var file_proto_RadarFc2_AckMsg_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x61, 0x64, 0x61, 0x72, 0x46, 0x63, 0x32,
	0x5f, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x46, 0x63, 0x32, 0x5f, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x7a,
	0x0a, 0x0f, 0x52, 0x61, 0x64, 0x61, 0x72, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x45, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x41, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x46, 0x63, 0x32,
	0x5f, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x41, 0x63, 0x6b,
	0x4d, 0x73, 0x67, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x6e,
	0x75, 0x41, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x33, 0x32, 0x61,
	0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x75,
	0x33, 0x32, 0x61, 0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x70, 0x0a, 0x14, 0x52, 0x61,
	0x64, 0x61, 0x72, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x4b, 0x5f, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x43, 0x4b, 0x5f, 0x44,
	0x45, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x4b, 0x5f, 0x47,
	0x45, 0x4e, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x4b, 0x5f,
	0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x04, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_RadarFc2_AckMsg_proto_rawDescOnce sync.Once
	file_proto_RadarFc2_AckMsg_proto_rawDescData = file_proto_RadarFc2_AckMsg_proto_rawDesc
)

func file_proto_RadarFc2_AckMsg_proto_rawDescGZIP() []byte {
	file_proto_RadarFc2_AckMsg_proto_rawDescOnce.Do(func() {
		file_proto_RadarFc2_AckMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RadarFc2_AckMsg_proto_rawDescData)
	})
	return file_proto_RadarFc2_AckMsg_proto_rawDescData
}

var file_proto_RadarFc2_AckMsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_RadarFc2_AckMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_RadarFc2_AckMsg_proto_goTypes = []interface{}{
	(RadarAckMsg_CodeType)(0), // 0: RadarFc2_AckMsg.RadarAckMsg_CodeType
	(*RadarAckMsgType)(nil),   // 1: RadarFc2_AckMsg.RadarAckMsgType
}
var file_proto_RadarFc2_AckMsg_proto_depIdxs = []int32{
	0, // 0: RadarFc2_AckMsg.RadarAckMsgType.enuAckCode:type_name -> RadarFc2_AckMsg.RadarAckMsg_CodeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_RadarFc2_AckMsg_proto_init() }
func file_proto_RadarFc2_AckMsg_proto_init() {
	if File_proto_RadarFc2_AckMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RadarFc2_AckMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RadarAckMsgType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RadarFc2_AckMsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_RadarFc2_AckMsg_proto_goTypes,
		DependencyIndexes: file_proto_RadarFc2_AckMsg_proto_depIdxs,
		EnumInfos:         file_proto_RadarFc2_AckMsg_proto_enumTypes,
		MessageInfos:      file_proto_RadarFc2_AckMsg_proto_msgTypes,
	}.Build()
	File_proto_RadarFc2_AckMsg_proto = out.File
	file_proto_RadarFc2_AckMsg_proto_rawDesc = nil
	file_proto_RadarFc2_AckMsg_proto_goTypes = nil
	file_proto_RadarFc2_AckMsg_proto_depIdxs = nil
}
