// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/RadarHc_Payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* @brief  message type
type MsgGenreType int32

const (
	MsgGenreType_REQUEST  MsgGenreType = 0 // request message
	MsgGenreType_RESPONSE MsgGenreType = 1 // response message
)

// Enum value maps for MsgGenreType.
var (
	MsgGenreType_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
	}
	MsgGenreType_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
	}
)

func (x MsgGenreType) Enum() *MsgGenreType {
	p := new(MsgGenreType)
	*p = x
	return p
}

func (x MsgGenreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgGenreType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_RadarHc_Payload_proto_enumTypes[0].Descriptor()
}

func (MsgGenreType) Type() protoreflect.EnumType {
	return &file_proto_RadarHc_Payload_proto_enumTypes[0]
}

func (x MsgGenreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgGenreType.Descriptor instead.
func (MsgGenreType) EnumDescriptor() ([]byte, []int) {
	return file_proto_RadarHc_Payload_proto_rawDescGZIP(), []int{0}
}

//* @brief  message model
type MsgModelType int32

const (
	MsgModelType_RESERVED           MsgModelType = 0 // reserved message model
	MsgModelType_RADAR_PARAM_CFG    MsgModelType = 1 // Radar parameter configuration message model
	MsgModelType_RADAR_ADC_ACQ_DATA MsgModelType = 2 // Radar ADC acquisition data message model
)

// Enum value maps for MsgModelType.
var (
	MsgModelType_name = map[int32]string{
		0: "RESERVED",
		1: "RADAR_PARAM_CFG",
		2: "RADAR_ADC_ACQ_DATA",
	}
	MsgModelType_value = map[string]int32{
		"RESERVED":           0,
		"RADAR_PARAM_CFG":    1,
		"RADAR_ADC_ACQ_DATA": 2,
	}
)

func (x MsgModelType) Enum() *MsgModelType {
	p := new(MsgModelType)
	*p = x
	return p
}

func (x MsgModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_RadarHc_Payload_proto_enumTypes[1].Descriptor()
}

func (MsgModelType) Type() protoreflect.EnumType {
	return &file_proto_RadarHc_Payload_proto_enumTypes[1]
}

func (x MsgModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgModelType.Descriptor instead.
func (MsgModelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_RadarHc_Payload_proto_rawDescGZIP(), []int{1}
}

//* @brief  Payload message model for communication between radar ECU and host computer
type RadarHc_PayloadType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U16ProjId   uint32       `protobuf:"varint,1,opt,name=u16ProjId,proto3" json:"u16ProjId,omitempty"`                                         // project identification
	EnuMsgGenre MsgGenreType `protobuf:"varint,2,opt,name=enuMsgGenre,proto3,enum=RadarFc2_ParamCfg.MsgGenreType" json:"enuMsgGenre,omitempty"` // message type
	EnuMsgModel MsgModelType `protobuf:"varint,3,opt,name=enuMsgModel,proto3,enum=RadarFc2_ParamCfg.MsgModelType" json:"enuMsgModel,omitempty"` // message Model
	PMsgStream  []byte       `protobuf:"bytes,4,opt,name=pMsgStream,proto3" json:"pMsgStream,omitempty"`                                        // message stream
}

func (x *RadarHc_PayloadType) Reset() {
	*x = RadarHc_PayloadType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RadarHc_Payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RadarHc_PayloadType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarHc_PayloadType) ProtoMessage() {}

func (x *RadarHc_PayloadType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RadarHc_Payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarHc_PayloadType.ProtoReflect.Descriptor instead.
func (*RadarHc_PayloadType) Descriptor() ([]byte, []int) {
	return file_proto_RadarHc_Payload_proto_rawDescGZIP(), []int{0}
}

func (x *RadarHc_PayloadType) GetU16ProjId() uint32 {
	if x != nil {
		return x.U16ProjId
	}
	return 0
}

func (x *RadarHc_PayloadType) GetEnuMsgGenre() MsgGenreType {
	if x != nil {
		return x.EnuMsgGenre
	}
	return MsgGenreType_REQUEST
}

func (x *RadarHc_PayloadType) GetEnuMsgModel() MsgModelType {
	if x != nil {
		return x.EnuMsgModel
	}
	return MsgModelType_RESERVED
}

func (x *RadarHc_PayloadType) GetPMsgStream() []byte {
	if x != nil {
		return x.PMsgStream
	}
	return nil
}

var File_proto_RadarHc_Payload_proto protoreflect.FileDescriptor

var file_proto_RadarHc_Payload_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x61, 0x64, 0x61, 0x72, 0x48, 0x63, 0x5f,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x46, 0x63, 0x32, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x43, 0x66, 0x67,
	0x22, 0xd9, 0x01, 0x0a, 0x13, 0x52, 0x61, 0x64, 0x61, 0x72, 0x48, 0x63, 0x5f, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x31, 0x36, 0x50,
	0x72, 0x6f, 0x6a, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x31, 0x36,
	0x50, 0x72, 0x6f, 0x6a, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0b, 0x65, 0x6e, 0x75, 0x4d, 0x73, 0x67,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x52, 0x61,
	0x64, 0x61, 0x72, 0x46, 0x63, 0x32, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x43, 0x66, 0x67, 0x2e,
	0x4d, 0x73, 0x67, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x65, 0x6e,
	0x75, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x65, 0x6e, 0x75,
	0x4d, 0x73, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x46, 0x63, 0x32, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x43,
	0x66, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x65, 0x6e, 0x75, 0x4d, 0x73, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x70, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2a, 0x29, 0x0a, 0x0c,
	0x4d, 0x73, 0x67, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x2a, 0x49, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x41, 0x44, 0x41, 0x52, 0x5f, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x43, 0x46, 0x47, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x41,
	0x44, 0x41, 0x52, 0x5f, 0x41, 0x44, 0x43, 0x5f, 0x41, 0x43, 0x51, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_RadarHc_Payload_proto_rawDescOnce sync.Once
	file_proto_RadarHc_Payload_proto_rawDescData = file_proto_RadarHc_Payload_proto_rawDesc
)

func file_proto_RadarHc_Payload_proto_rawDescGZIP() []byte {
	file_proto_RadarHc_Payload_proto_rawDescOnce.Do(func() {
		file_proto_RadarHc_Payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RadarHc_Payload_proto_rawDescData)
	})
	return file_proto_RadarHc_Payload_proto_rawDescData
}

var file_proto_RadarHc_Payload_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_RadarHc_Payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_RadarHc_Payload_proto_goTypes = []interface{}{
	(MsgGenreType)(0),           // 0: RadarFc2_ParamCfg.MsgGenreType
	(MsgModelType)(0),           // 1: RadarFc2_ParamCfg.MsgModelType
	(*RadarHc_PayloadType)(nil), // 2: RadarFc2_ParamCfg.RadarHc_PayloadType
}
var file_proto_RadarHc_Payload_proto_depIdxs = []int32{
	0, // 0: RadarFc2_ParamCfg.RadarHc_PayloadType.enuMsgGenre:type_name -> RadarFc2_ParamCfg.MsgGenreType
	1, // 1: RadarFc2_ParamCfg.RadarHc_PayloadType.enuMsgModel:type_name -> RadarFc2_ParamCfg.MsgModelType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_RadarHc_Payload_proto_init() }
func file_proto_RadarHc_Payload_proto_init() {
	if File_proto_RadarHc_Payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RadarHc_Payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RadarHc_PayloadType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RadarHc_Payload_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_RadarHc_Payload_proto_goTypes,
		DependencyIndexes: file_proto_RadarHc_Payload_proto_depIdxs,
		EnumInfos:         file_proto_RadarHc_Payload_proto_enumTypes,
		MessageInfos:      file_proto_RadarHc_Payload_proto_msgTypes,
	}.Build()
	File_proto_RadarHc_Payload_proto = out.File
	file_proto_RadarHc_Payload_proto_rawDesc = nil
	file_proto_RadarHc_Payload_proto_goTypes = nil
	file_proto_RadarHc_Payload_proto_depIdxs = nil
}
